export default {
  "FFXIV Weather Bell": "最终幻想14天气时钟",

  "Zone": "地区",
  "Weather": "天气",
  "Previous Weather": "前置天气",
  "Time": "时间",
  "Any": "任意",
  "Local Time": "本地时间",
  "Eorzea Time": "艾欧泽亚时间",
  "Start Time": "开始时间",
  "End Time": "结束时间",
  "Weathers": "天气",
  "Show more": "显示更多",

  "Limsa Lominsa": "海都",
  "Middle La Noscea": "中拉",
  "Lower La Noscea": "拉低",
  "Eastern La Noscea": "东拉",
  "Western La Noscea": "西拉",
  "Upper La Noscea": "拉高",
  "Outer La Noscea": "拉外",
  "The Mist": "海雾村",
  "Gridania": "森都",
  "Central Shroud": "中森",
  "East Shroud": "东森",
  "South Shroud": "南森",
  "North Shroud": "北森",
  "The Lavender Beds": "苗圃",
  "Ul'dah": "沙都",
  "Western Thanalan": "西萨",
  "Central Thanalan": "中萨",
  "Eastern Thanalan": "东萨",
  "Southern Thanalan": "南萨",
  "Northern Thanalan": "北萨",
  "The Goblet": "高脚孤丘",
  "Ishgard": "伊修加德",
  "Coerthas Central Highlands": "中高",
  "Coerthas Western Highlands": "西高",
  "The Sea of Clouds": "云海",
  "Azys Lla": "魔大陆",
  "The Diadem": "空岛",
  "Idyllshire": "田园郡",
  "The Dravanian Forelands": "龙高",
  "The Dravanian Hinterlands": "龙低",
  "The Churning Mists": "雾海",
  "Mor Dhona": "摩杜纳",
  "Rhalgr's Reach": "神拳痕",
  "The Fringes": "边区",
  "The Peaks": "山区",
  "The Lochs": "湖区",
  "Kugane": "黄金港",
  "Shirogane": "白银乡",
  "The Ruby Sea": "红玉海",
  "Yanxia": "延夏",
  "The Azim Steppe": "草原",
  "Eureka Anemos": "常风",
  "Eureka Pagos": "恒冰",
  "Eureka Pyros": "涌火",
  "Eureka Hydatos": "丰水",
  "Bozjan Southern Front": "博兹雅战线",
  "The Crystarium": "水晶都",
  "Eulmore": "游末邦",
  "Lakeland": "雷克兰德",
  "Kholusia": "珂露西亚",
  "Amh Araeng": "安穆艾兰",
  "Il Mheg": "伊尔美格",
  "The Rak'tika Greatwood": "LaHee",
  "The Tempest": "黑风海",

  "Clouds": "阴云",
  "Clear Skies": "碧空",
  "Fair Skies": "晴朗",
  "Fog": "薄雾",
  "Rain": "小雨",
  "Wind": "微风",
  "Showers": "暴雨",
  "Gales": "强风",
  "Thunder": "打雷",
  "Thunderstorms": "雷雨",
  "Dust Storms": "扬沙",
  "Heat Waves": "热浪",
  "Gloom": "妖雾",
  "Snow": "小雪",
  "Blizzards": "暴雪",
  "Umbral Wind": "灵风",
  "Umbral Static": "灵电",
} as { [index: string]: string }
