export default {
  'FFXIV Weather Lookup': {
    en: 'FFXIV Weather Lookup',
    de: 'FFXIV Weather Lookup',
    fr: 'FFXIV Weather Lookup',
    ja: 'FFXIV Weather Lookup',
    cn: '最终幻想14天气查询',
  },

  'Zone': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '地区',
  },
  'Select Zone': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '请选择一个地区',
  },
  'Weather': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '天气',
  },
  'Previous Weather': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '前置天气',
  },
  'Right click to multiple select': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '右击多选',
  },
  'Time': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '时间',
  },
  'Click start time then select a range': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '点击开始时间然后选择一个时间段',
  },
  'Any': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '任意',
  },
  'Found {count} matches in next {future} earth days': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '未来 {future} 地球天内共有 {count} 个时段符合条件',
  },
  'Showing future weather list, select some conditions to query matched periods': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '正在展示未来的天气序列，选择一些条件可以查询符合的时段',
  },
  'Local Time': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '本地时间',
  },
  'Eorzea Time': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '艾欧泽亚时间',
  },
  'Start Time': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '开始时间',
  },
  'End Time': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '结束时间',
  },
  'Weathers': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '天气',
  },
  'Show more': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '显示更多',
  },
  'License': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '许可协议',
  },
  'Code': {
    en: '',
    de: '',
    fr: '',
    ja: '',
    cn: '源代码',
  },

  'Limsa Lominsa': {
    en: 'Limsa',
    de: 'Limsa',
    fr: 'Limsa',
    ja: 'リムサ',
    cn: '海都',
  },
  'Middle La Noscea': {
    en: 'Middle',
    de: 'Zentrales',
    fr: 'Centrale',
    ja: '中ラ',
    cn: '中拉',
  },
  'Lower La Noscea': {
    en: 'Lower',
    de: 'Unteres',
    fr: 'Basse',
    ja: '低ラ',
    cn: '拉低',
  },
  'Eastern La Noscea': {
    en: 'Eastern',
    de: 'Östliches',
    fr: 'Orientale',
    ja: '東ラ',
    cn: '东拉',
  },
  'Western La Noscea': {
    en: 'Western',
    de: 'Westliches',
    fr: 'Noscea',
    ja: '西ラ',
    cn: '西拉',
  },
  'Upper La Noscea': {
    en: 'Upper',
    de: 'Oberes',
    fr: 'Haute',
    ja: '高ラ',
    cn: '拉高',
  },
  'Outer La Noscea': {
    en: 'Outer',
    de: 'Äußeres',
    fr: 'Noscea',
    ja: '外ラ',
    cn: '拉外',
  },
  'The Mist': {
    en: 'Mist',
    de: 'Nebels',
    fr: 'Brumée',
    ja: 'ミスト',
    cn: '海雾村',
  },
  'Gridania': {
    en: 'Gridania',
    de: 'Gridania',
    fr: 'Gridania',
    ja: 'グリダニア',
    cn: '森都',
  },
  'Central Shroud': {
    en: 'Central',
    de: 'Tiefer',
    fr: 'Centrale',
    ja: '中森',
    cn: '中森',
  },
  'East Shroud': {
    en: 'East',
    de: 'Ost',
    fr: 'L\'est',
    ja: '東森',
    cn: '东森',
  },
  'South Shroud': {
    en: 'South',
    de: 'Süd',
    fr: 'Sud',
    ja: '南森',
    cn: '南森',
  },
  'North Shroud': {
    en: 'North',
    de: 'Nord',
    fr: 'Nord',
    ja: '北森',
    cn: '北森',
  },
  'The Lavender Beds': {
    en: 'Lavender',
    de: 'Lavendelbeete',
    fr: 'Lavandière',
    ja: 'ラベンダー',
    cn: '苗圃',
  },
  'Ul\'dah': {
    en: 'Ul\'dah',
    de: 'Kreuzgang',
    fr: 'Ul\'dah',
    ja: 'ウルダハ',
    cn: '沙都',
  },
  'Western Thanalan': {
    en: 'Western',
    de: 'Westliches',
    fr: 'Occidental',
    ja: '西ザ',
    cn: '西萨',
  },
  'Central Thanalan': {
    en: 'Central',
    de: 'Zentrales',
    fr: 'Central',
    ja: '中ザ',
    cn: '中萨',
  },
  'Eastern Thanalan': {
    en: 'Eastern',
    de: 'Östliches',
    fr: 'Oriental',
    ja: '東ザ',
    cn: '东萨',
  },
  'Southern Thanalan': {
    en: 'Southern',
    de: 'Südliches',
    fr: 'Méridional',
    ja: '南ザ',
    cn: '南萨',
  },
  'Northern Thanalan': {
    en: 'Northern',
    de: 'Nördliches',
    fr: 'Septentrional',
    ja: '北ザ',
    cn: '北萨',
  },
  'The Goblet': {
    en: 'Goblet',
    de: 'Kelchkuppe',
    fr: 'La Coup',
    ja: 'ゴブレット',
    cn: '高脚孤丘',
  },
  'Ishgard': {
    en: 'Ishgard',
    de: 'Ishgard',
    fr: 'Ishgard',
    ja: 'イシュガルド',
    cn: '伊修加德',
  },
  'Coerthas Central Highlands': {
    en: 'Central',
    de: 'Zentrales',
    fr: 'Central',
    ja: 'ク中',
    cn: '中高',
  },
  'Coerthas Western Highlands': {
    en: 'Western',
    de: 'Westliches',
    fr: 'Occidental',
    ja: 'ク西',
    cn: '西高',
  },
  'The Sea of Clouds': {
    en: 'Sea of Clouds',
    de: 'Wolkenmeer',
    fr: 'L\'Écume des cieux',
    ja: 'ア雲',
    cn: '云海',
  },
  'Azys Lla': {
    en: 'Azys Lla',
    de: 'Azys Lla',
    fr: 'Azys Lla',
    ja: '魔大陸',
    cn: '魔大陆',
  },
  'The Diadem': {
    en: 'Diadem',
    de: 'Diadem',
    fr: 'Diadème',
    ja: 'ディアデム',
    cn: '空岛',
  },
  'Idyllshire': {
    en: 'Idyllshire',
    de: 'Frohehalde',
    fr: 'Idyllée',
    ja: 'イディルシャイア',
    cn: '田园郡',
  },
  'The Dravanian Forelands': {
    en: 'Forelands',
    de: 'Vorland',
    fr: 'Avant-pays',
    ja: '高ド',
    cn: '龙高',
  },
  'The Dravanian Hinterlands': {
    en: 'Hinterlands',
    de: 'Hinterland',
    fr: 'Arrière-pays',
    ja: '低ド',
    cn: '龙低',
  },
  'The Churning Mists': {
    en: 'Churning Mists',
    de: 'Wallende Nebel',
    fr: 'L\'Écume des cieux',
    ja: 'ド雲',
    cn: '雾海',
  },
  'Mor Dhona': {
    en: 'Mor Dhona',
    de: 'Mor Dhona',
    fr: 'Mor Dhona',
    ja: 'モードゥナ',
    cn: '摩杜纳',
  },
  'Rhalgr\'s Reach': {
    en: 'Rhalgr',
    de: 'Rhalgr',
    fr: 'Rhalgr',
    ja: 'ラールガー',
    cn: '神拳痕',
  },
  'The Fringes': {
    en: 'Fringes',
    de: 'Grenzland',
    fr: 'Marges',
    ja: 'ギ辺',
    cn: '边区',
  },
  'The Peaks': {
    en: 'Peaks',
    de: 'Zinnen',
    fr: 'Pics',
    ja: 'ギ山',
    cn: '山区',
  },
  'The Lochs': {
    en: 'Lochs',
    de: 'Fenn',
    fr: 'Lacs',
    ja: 'ギ湖',
    cn: '湖区',
  },
  'Kugane': {
    en: 'Kugane',
    de: 'Kugane',
    fr: 'Kugane',
    ja: 'クガネ',
    cn: '黄金港',
  },
  'Shirogane': {
    en: 'Shirogane',
    de: 'Shirogane',
    fr: 'Shirogane',
    ja: 'シロガネ',
    cn: '白银乡',
  },
  'The Ruby Sea': {
    en: 'Ruby Sea',
    de: 'Rubinsee',
    fr: 'Mer de Rubis',
    ja: '紅玉海',
    cn: '红玉海',
  },
  'Yanxia': {
    en: 'Yanxia',
    de: 'Yanxia',
    fr: 'Yanxia',
    ja: 'ヤンサ',
    cn: '延夏',
  },
  'The Azim Steppe': {
    en: 'Azim Steppe',
    de: 'Azim-Steppe',
    fr: 'Steppe d\'Azim',
    ja: 'アジムステップ',
    cn: '草原',
  },
  'Eureka Anemos': {
    en: 'Anemos',
    de: 'Anemos',
    fr: 'Anemos',
    ja: 'アネモス',
    cn: '常风',
  },
  'Eureka Pagos': {
    en: 'Pagos',
    de: 'Pagos',
    fr: 'Pagos',
    ja: 'パゴス',
    cn: '恒冰',
  },
  'Eureka Pyros': {
    en: 'Pyros',
    de: 'Pyros',
    fr: 'Pyros',
    ja: 'ピューロス',
    cn: '涌火',
  },
  'Eureka Hydatos': {
    en: 'Hydatos',
    de: 'Hydatos',
    fr: 'Hydatos',
    ja: 'ヒュダトス',
    cn: '丰水',
  },
  'Bozjan Southern Front': {
    en: 'Bozjan Front',
    de: 'Bozja-Front',
    fr: 'Front de Bozja',
    ja: 'ボズヤ戦線',
    cn: '博兹雅战线',
  },
  'Zadnor': {
    en: 'Zadnor',
    de: 'Zadnor',
    fr: 'Zadnor',
    ja: 'ザトゥノル',
    cn: '高原',
  },
  'The Crystarium': {
    en: 'Crystarium',
    de: 'Crystarium',
    fr: 'Cristarium',
    ja: 'クリスタリウム',
    cn: '水晶都',
  },
  'Eulmore': {
    en: 'Eulmore',
    de: 'Eulmore',
    fr: 'Eulmore',
    ja: 'ユールモア',
    cn: '游末邦',
  },
  'Lakeland': {
    en: 'Lakeland',
    de: 'Seenland',
    fr: 'Grand-Lac',
    ja: 'レイクランド',
    cn: '雷克兰德',
  },
  'Kholusia': {
    en: 'Kholusia',
    de: 'Kholusia',
    fr: 'Kholusia',
    ja: 'コルシア',
    cn: '珂露西亚',
  },
  'Amh Araeng': {
    en: 'Amh Araeng',
    de: 'Amh Araeng',
    fr: 'Amh Araeng',
    ja: 'アム・アレーン',
    cn: '安穆艾兰',
  },
  'Il Mheg': {
    en: 'Il Mheg',
    de: 'Il Mheg',
    fr: 'Il Mheg',
    ja: 'イル・メグ',
    cn: '伊尔美格',
  },
  'The Rak\'tika Greatwood': {
    en: 'LaHee',
    de: 'LaHee',
    fr: 'LaHee',
    ja: 'LaHee',
    cn: 'LaHee',
  },
  'The Tempest': {
    en: 'Tempest',
    de: 'Tempest',
    fr: 'Tempête',
    ja: 'テンペスト',
    cn: '黑风海',
  },
  'Old Sharlayan': {
    en: 'Sharlayan',
    de: 'Sharlayan',
    fr: 'Sharlayan',
    ja: 'シャーレアン',
    cn: '萨雷安',
  },
  'Radz-at-Han': {
    en: 'Radz-at-Han',
    de: 'Radz-at-Han',
    fr: 'Radz-at-Han',
    ja: 'ラザハン',
    cn: '拉札罕',
  },
  'Labyrinthos': {
    en: 'Labyrinthos',
    de: 'Labyrinthos',
    fr: 'Labyrinthos',
    ja: 'ラヴィリンソス',
    cn: '迷津',
  },
  'Thavnair': {
    en: 'Thavnair',
    de: 'Thavnair',
    fr: 'Thavnair',
    ja: 'サベネア',
    cn: '萨维奈',
  },
  'Garlemald': {
    en: 'Garlemald',
    de: 'Garlemald',
    fr: 'Garlemald',
    ja: 'ガレマルド',
    cn: '加雷马',
  },
  'Mare Lamentorum': {
    en: 'Mare Lamentorum',
    de: 'Mare Lamentorum',
    fr: 'Mare Lamentorum',
    ja: '嘆きの海',
    cn: '叹息海',
  },
  'Elpis': {
    en: 'Elpis',
    de: 'Elpis',
    fr: 'Elpis',
    ja: 'エルピス',
    cn: 'エルピス',
  },
  'Ultima Thule': {
    en: 'Thule',
    de: 'Thule',
    fr: 'Thulé',
    ja: 'トゥーレ',
    cn: 'トゥーレ',
  },

  'Clear Skies': {
    en: 'Clear',
    de: 'Klar',
    fr: 'Dégagé',
    ja: '快晴',
    cn: '碧空',
  },
  'Fair Skies': {
    en: 'Fair',
    de: 'Heiter',
    fr: 'Clair',
    ja: '晴れ',
    cn: '晴朗',
  },
  'Clouds': {
    en: 'Clouds',
    de: 'Wolkig',
    fr: 'Couvert',
    ja: '曇り',
    cn: '阴云',
  },
  'Fog': {
    en: 'Fog',
    de: 'Neblig',
    fr: 'Brouillard',
    ja: '霧',
    cn: '薄雾',
  },
  'Wind': {
    en: 'Wind',
    de: 'Windig',
    fr: 'Vent',
    ja: '風',
    cn: '微风',
  },
  'Gales': {
    en: 'Gales',
    de: 'Stürmisch',
    fr: 'Vents Violents',
    ja: '暴風',
    cn: '强风',
  },
  'Rain': {
    en: 'Rain',
    de: 'Regnerisch',
    fr: 'Pluie',
    ja: '雨',
    cn: '小雨',
  },
  'Showers': {
    en: 'Showers',
    de: 'Wolkenbruch',
    fr: 'Torrentielle',
    ja: '暴雨',
    cn: '暴雨',
  },
  'Thunder': {
    en: 'Thunder',
    de: 'Gewittrig',
    fr: 'Orages',
    ja: '雷',
    cn: '打雷',
  },
  'Thunderstorms': {
    en: 'Thunderstorms',
    de: 'Gewitter',
    fr: 'Orages violents',
    ja: '雷雨',
    cn: '雷雨',
  },
  'Dust Storms': {
    en: 'Dust',
    de: 'Staubig',
    fr: 'Poussière',
    ja: '砂塵',
    cn: '扬沙',
  },
  'Heat Waves': {
    en: 'Heat Waves',
    de: 'Gluthitze',
    fr: 'Torride',
    ja: '灼熱波',
    cn: '热浪',
  },
  'Snow': {
    en: 'Snow',
    de: 'Schnee',
    fr: 'Neige',
    ja: '雪',
    cn: '小雪',
  },
  'Blizzards': {
    en: 'Blizzards',
    de: 'Schneesturm',
    fr: 'Blizzard',
    ja: '吹雪',
    cn: '暴雪',
  },
  'Gloom': {
    en: 'Gloom',
    de: 'Unheimlich',
    fr: 'Nébuleux',
    ja: '妖霧',
    cn: '妖雾',
  },
  'Umbral Wind': {
    en: 'Umbral Wind',
    de: 'Schattenwind',
    fr: 'Vent ombral',
    ja: '霊風',
    cn: '灵风',
  },
  'Umbral Static': {
    en: 'Umbral Static',
    de: 'Schattengewitter',
    fr: 'Charges ombrales',
    ja: '放電',
    cn: '灵电',
  },
  'Moon Dust': {
    en: 'Moon Dust',
    de: 'Mondstaubig',
    fr: 'Tempêtes de régolithe',
    ja: '月砂塵',
    cn: '月砂塵',
  },
  'Astromagnetic Storm': {
    en: 'Astromagnetic Storm',
    de: 'Magnetsturm',
    fr: 'Astromagnétique',
    ja: '磁気嵐',
    cn: '磁暴',
  },
} as { [index: string]: { [index: string]: string } };
